name: Deployment

# on:
#   push:
#     branches:
#       - main

on: [push] # TODO delete this before PR

jobs:
  Deploy-to-main:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.8
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true
      - name: Install wasm-opt
        run: sudo apt update && sudo apt install -y binaryen clang # && sudo rm -rf /var/lib/apt/lists/*
      - name: Build secret gateway contract
        run: cd TNLS-Gateways/secret/ && make build-mainnet
      - name: Build secret sample contract
        run: cd TNLS-Gateways/secret/tests/example-private-contract && make build-mainnet
      - name: Deploy Secret Contracts
        env:
          MNEMONIC: ${{ secrets.SECRET_WALLET_MNEMONIC }}
        run: |
          touch .env
          echo MNEMONIC="$MNEMONIC" >> .env
          echo GRPC_WEB_URL='"https://grpc.testnet.secretsaturn.net"'' >> .env
          echo CHAIN_ID='"pulsar-2"' >> .env
          cat .env
      - name: Get secret contract verification key
        run:
          echo "Unimplemented"
      - name: Build public contract
        run:
          echo "Unimplemented"
      - name: Deploy public contract
        run:
          echo "Unimplemented"
      - name: Deploy sample scrt contracts
        run:
          echo "Unimplemented"
      - name: Deploy sample eth contracts
        run:
          echo "Unimplemented"
      # - name: Install python dependencies
      #   working-directory: ./TNLS-Relayers
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Write webserver Config Files
      #   working-directory: ./TNLS-Relayers
      #   env:
      #     INFURA_ENDPOINT: ${{ secrets.INFURA_ENDPOINT }}
      #   run: |
      #     touch infura_api_endpoint.txt
      #     echo "$INFURA_ENDPOINT" > infura_api_endpoint.txt
      #     echo "Unimplemented"
      - name: Deploy webserver to heroku
        run:
          echo "Unimplemented"
