name: Foundry Tests
on:
  push:
    paths:
      - 'public-gateway/**'

jobs:
  tests:
    name: TNLS eth gateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        working-directory: ./public-gateway
        run: forge install

      - name: Run tests
        working-directory: ./public-gateway
        run: forge test -vvv

      - name: Check gas snapshots
        run: forge snapshot --check