name: Python package

on: [push]

jobs:
  build-and-test-python:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: ./TNLS-Relayers
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Write Config File
        working-directory: ./TNLS-Relayers
        env:
          INFURA_ENDPOINT: ${{ secrets.INFURA_ENDPOINT }}
        run: |
          touch infura_api_endpoint.txt
          echo "$INFURA_ENDPOINT" > infura_api_endpoint.txt
      - name: Test with pytest
        working-directory: ./TNLS-Relayers/relayer_tests
        run: |
          pytest