name: Deployment

on:
  push:
    branches:
      - leorf/fix-web-and-eth-error

jobs:
  Deploy-to-main:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Deploy webserver to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "atbash-demo-server"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
